language: node_js
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn run test
  - yarn run codecov
go:
  - "1.11.x"
node_js:
  - "10.13"
